/**
 * Represents the gamepad buttons used in the input system.
 *
 * @export
 * @enum {number}
 */
export enum GamepadButton {
    Button0 = 0,
    Button1 = 1,
    Button2 = 2,
    Button3 = 3,
    Button4 = 4,
    Button5 = 5,
    Button6 = 6,
    Button7 = 7,
    Button8 = 8,
    Button9 = 9,
    Button10 = 10,
    Button11 = 11,
    Button12 = 12,
    Button13 = 13,
    Button14 = 14,
    Button15 = 15,
    Button16 = 16,

    A = Button0,
    B = Button1,
    X = Button2,
    Y = Button3,
    LB = Button4,
    RB = Button5,
    LT = Button6,
    RT = Button7,
    View = Button8,
    Menu = Button9,
    LeftStick = Button10,
    RightStick = Button11,
    Up = Button12,
    Down = Button13,
    Left = Button14,
    Right = Button15,
    Home = Button16,
    Xbox = Button16,
    Guide = Button16,

    Cross = Button0,
    Circle = Button1,
    Square = Button2,
    Triangle = Button3,
    L1 = Button4,
    R1 = Button5,
    L2 = Button6,
    R2 = Button7,
    Select = Button8,
    Start = Button9,
    L3 = Button10,
    R3 = Button11,
    TouchPad = Button16,
}
